@startuml

package "preparations" {
  [dotfiles]
  [symlinks]
}

package "zsh-plugins" {
  [zsh-autopair]
  [zsh-autosuggestions]
  [zsh-fast-syntax-highlighting]
  [zsh-fzf-git]
  [zsh-fzf-kill]
  [zsh-interactive-cd]
}

package "zsh-themes" {
  [zsh-powerlevel10k]
}

[stow] ..> [bash-completion]
[stow] ..> [git-completion]
[stow] ..> [fasd]
[stow] ..> [fzf]
[stow] ..> [gcc]
[stow] ..> [oh-my-zsh]
[stow] ..> [patchelf]
[stow] ..> [pyenv]

[patchelf] ..> [gcc]
[patchelf] ..> [cmake]

[gcc] ..> [aspell]
[gcc] ..> [binutils]
[gcc] ..> [bison]
[gcc] ..> [curl]
[gcc] ..> [gmp]
[gcc] ..> [grpc]
[gcc] ..> [jansson]
[gcc] ..> [libevent]
[gcc] ..> [libtasn1]
[gcc] ..> [ncurses]
[gcc] ..> [rustup]
[gcc] ..> [sqlite]
[gcc] ..> [tar]

[cmake] ..> [ccls]
[cmake] ..> [grpc]
[cmake] ..> [llvm-project]
[cmake] ..> [libevent]

[pyenv] ..> [pythons]
[sqlite] ..> [pythons]

[pythons] ..> [bear]
[pythons] ..> [git-review]
[pythons] ..> [libxml2]
[pythons] ..> [ranger]
[pythons] ..> [repo]

[gmp] ..> [nettle]
[gmp] ..> [gnutls]

[libtasn1] ..> [gnutls]
[nettle] ..> [gnutls]

[gnutls] ..> [emacs]
[jansson] ..> [emacs]
[libxml2] ..> [emacs]

[aspell] ..> [aspell-en]

[binutils] ..> [llvm-project]

[grpc] ..> [llvm-project]

[pythons] ..> [llvm-project]

[tar] ..> [libtool]

[ncurses] ..> [htop]
[ncurses] ..> [less]
[ncurses] ..> [llvm-project]
[ncurses] ..> [tig]
[ncurses] ..> [tmux]
[ncurses] ..> [zsh]

[libevent] ..> [tmux]

[curl] ..> [git]

[git] ..> [git-lfs]

[llvm-project] ..> [ccls]

[rustup] ..> [bat]
[rustup] ..> [delta]
[rustup] ..> [fd]
[rustup] ..> [lsd]
[rustup] ..> [ripgrep]
[rustup] ..> [sad]

@enduml
